### ISSUE TITLE
Add error handling for when pg_restore fails

### ISSUE THREAD

**Issue by insidus341** [mjuopperi/eve-sde-postgres-updater#1]
If pg_restore fails, the `.update.log` file is still created which then requires removal before running `./sde_updater.sh` again. 

Example error: 
```
pg_restore: connecting to database for restore
pg_restore: error: connection to database "eve-sde" failed: FATAL:  role "eve-sde" does not exist
```

**Comment by mjuopperi** [comment]
Good catch! I'll have a look at this later.

**Comment by mjuopperi** [comment]
Fixed in https://github.com/mjuopperi/eve-sde-postgres-updater/commit/b272672064a94aed0cc3a9f4128bace6ce772694
